packages: 

substitutions:

esphome:
  name: ${display_name}
  friendly_name: ${display_friendly_name}
  comment: embiontec Wall display
  includes:
    - <sstream>
    - <algorithm>
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    - priority: 400
      then:
        - lambda: |-
            id(i18n_translations).set_current_locale(id(current_language));
        #- script.execute: update_loading_pageota_password
        - script.execute: update_loading_page
    - priority: -100
      then:
        - lvgl.roller.update:
            id: backlight_settings_sleep_time_roller
            selected_index: !lambda return id(display_timeout);

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      loop_task_stack_size: 8192
    sdkconfig_options:
      # CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: y
      # CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      # CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      # CONFIG_ESP_MAIN_TASK_STACK_SIZE: "16384"
      # CONFIG_ESP_MAIN_TASK_STACK_SIZE: "65536"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "60"
      # CONFIG_FREERTOS_USE_TRACE_FACILITY: "y"
      # CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS: "y"
      # CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS: "y"
      # CONFIG_FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER: "y"

psram:
  mode: octal
  speed: 80MHz


  logger:
  level: debug
  logs:
    lvgl: info
  hardware_uart: UART0

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  on_connect:
    - lvgl.label.update:
        id: wifi_status
        text_color: color_green
  on_disconnect:
    - lvgl.label.update:
        id: wifi_status
        text_color: color_steel_blue
ap:
  ssid: "WallDisplay Fallback Hotspot"
  password: "embinotec"
  ap_timeout: 10s

captive_portal:
  

improv_serial:


output:
    # Backlight LED
  - platform: ledc
    pin: GPIO38
    id: backlight_output
    frequency: 100Hz

i2c:
  - id: bus_a
    sda: GPIO19
    scl:
      number: GPIO45
      ignore_strapping_warning: true
    frequency: 100kHz


touchscreen:
  platform: gt911
  id: touchscreen_id
  transform:
    mirror_x: false
    mirror_y: false
  display: ${display_name}
  on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: display_backlight

  # on_touch:
  #   - lambda: |-
  #         ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
  #             touch.x,
  #             touch.y,
  #             touch.x_raw,
  #             touch.y_raw
  #             );

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

# display:
#   - platform: mipi_rgb
#     id: ${display_name}
#     model: GUITION-4848S040
#     rotation: 180

display:
  - platform: st7701s
    id: ${display_name}
    update_interval: never
    auto_clear_enabled: false
    data_rate: 2MHz
    spi_mode: MODE3
    color_order: RGB
    invert_colors: false
    dimensions:
      width: 480
      height: 480
    transform:
      mirror_x: false
      mirror_y: false
    cs_pin: 39
      # reset not defined 
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    init_sequence: 
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    pclk_frequency: 12MHz
    pclk_inverted: false
    data_pins:
      red:
        - 11         # R1
        - 12         # R2
        - 13         # R3
        - 14         # R4
        - 0          # R5
      green:
        - 8          # G0
        - 20         # G1
        - 3          # G2
        - 46         # G3
        - 9          # G4
        - 10         # G5 
      blue:
        - 4          # B1
        - 5          # B2
        - 6          # B3
        - 7          # B4
        - 15         # B5
